// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqUtT27O5TahpRh3KRWwh7zptLAm8hcU4',
    appId: '1:1063143165631:web:10717a79edc7f6cef5400a',
    messagingSenderId: '1063143165631',
    projectId: 'task-26933',
    authDomain: 'task-26933.firebaseapp.com',
    storageBucket: 'task-26933.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk_Y-2m6dPVoDVik5uKu78LSHz2X-93IA',
    appId: '1:1063143165631:android:a3693d1b356b161df5400a',
    messagingSenderId: '1063143165631',
    projectId: 'task-26933',
    storageBucket: 'task-26933.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_4oBTLCqC9knRoRbewBHDgbPs0Ela-tM',
    appId: '1:1063143165631:ios:8cb163984df5e75af5400a',
    messagingSenderId: '1063143165631',
    projectId: 'task-26933',
    storageBucket: 'task-26933.firebasestorage.app',
    iosBundleId: 'com.example.taskatApp',
  );
}
